/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace CWrapper {

using System;
using System.Runtime.InteropServices;

public class CharVector : IDisposable, System.Collections.IEnumerable
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IList<char>
#endif
 {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CharVector(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CharVector obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CharVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MMCoreCSPINVOKE.delete_CharVector(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public CharVector(System.Collections.ICollection c) : this() {
    if (c == null)
      throw new ArgumentNullException("c");
    foreach (char element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public char this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array)
#else
  public void CopyTo(char[] array)
#endif
  {
    CopyTo(0, array, 0, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array, int arrayIndex)
#else
  public void CopyTo(char[] array, int arrayIndex)
#endif
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(int index, System.Array array, int arrayIndex, int count)
#else
  public void CopyTo(int index, char[] array, int arrayIndex, int count)
#endif
  {
    if (array == null)
      throw new ArgumentNullException("array");
    if (index < 0)
      throw new ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

#if !SWIG_DOTNET_1
  System.Collections.Generic.IEnumerator<char> System.Collections.Generic.IEnumerable<char>.GetEnumerator() {
    return new CharVectorEnumerator(this);
  }
#endif

  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return new CharVectorEnumerator(this);
  }

  public CharVectorEnumerator GetEnumerator() {
    return new CharVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class CharVectorEnumerator : System.Collections.IEnumerator
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IEnumerator<char>
#endif
  {
    private CharVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public CharVectorEnumerator(CharVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public char Current {
      get {
        if (currentIndex == -1)
          throw new InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new InvalidOperationException("Collection modified.");
        return (char)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new InvalidOperationException("Collection modified.");
      }
    }

#if !SWIG_DOTNET_1
    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
#endif
  }

  public void Clear() {
    MMCoreCSPINVOKE.CharVector_Clear(swigCPtr);
  }

  public void Add(char x) {
    MMCoreCSPINVOKE.CharVector_Add(swigCPtr, x);
  }

  private uint size() {
    uint ret = MMCoreCSPINVOKE.CharVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = MMCoreCSPINVOKE.CharVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    MMCoreCSPINVOKE.CharVector_reserve(swigCPtr, n);
  }

  public CharVector() : this(MMCoreCSPINVOKE.new_CharVector__SWIG_0(), true) {
  }

  public CharVector(CharVector other) : this(MMCoreCSPINVOKE.new_CharVector__SWIG_1(CharVector.getCPtr(other)), true) {
    if (MMCoreCSPINVOKE.SWIGPendingException.Pending) throw MMCoreCSPINVOKE.SWIGPendingException.Retrieve();
  }

  public CharVector(int capacity) : this(MMCoreCSPINVOKE.new_CharVector__SWIG_2(capacity), true) {
    if (MMCoreCSPINVOKE.SWIGPendingException.Pending) throw MMCoreCSPINVOKE.SWIGPendingException.Retrieve();
  }

  private char getitemcopy(int index) {
    char ret = MMCoreCSPINVOKE.CharVector_getitemcopy(swigCPtr, index);
    if (MMCoreCSPINVOKE.SWIGPendingException.Pending) throw MMCoreCSPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private char getitem(int index) {
    char ret = MMCoreCSPINVOKE.CharVector_getitem(swigCPtr, index);
    if (MMCoreCSPINVOKE.SWIGPendingException.Pending) throw MMCoreCSPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, char val) {
    MMCoreCSPINVOKE.CharVector_setitem(swigCPtr, index, val);
    if (MMCoreCSPINVOKE.SWIGPendingException.Pending) throw MMCoreCSPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(CharVector values) {
    MMCoreCSPINVOKE.CharVector_AddRange(swigCPtr, CharVector.getCPtr(values));
    if (MMCoreCSPINVOKE.SWIGPendingException.Pending) throw MMCoreCSPINVOKE.SWIGPendingException.Retrieve();
  }

  public CharVector GetRange(int index, int count) {
    IntPtr cPtr = MMCoreCSPINVOKE.CharVector_GetRange(swigCPtr, index, count);
    CharVector ret = (cPtr == IntPtr.Zero) ? null : new CharVector(cPtr, true);
    if (MMCoreCSPINVOKE.SWIGPendingException.Pending) throw MMCoreCSPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, char x) {
    MMCoreCSPINVOKE.CharVector_Insert(swigCPtr, index, x);
    if (MMCoreCSPINVOKE.SWIGPendingException.Pending) throw MMCoreCSPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, CharVector values) {
    MMCoreCSPINVOKE.CharVector_InsertRange(swigCPtr, index, CharVector.getCPtr(values));
    if (MMCoreCSPINVOKE.SWIGPendingException.Pending) throw MMCoreCSPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    MMCoreCSPINVOKE.CharVector_RemoveAt(swigCPtr, index);
    if (MMCoreCSPINVOKE.SWIGPendingException.Pending) throw MMCoreCSPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    MMCoreCSPINVOKE.CharVector_RemoveRange(swigCPtr, index, count);
    if (MMCoreCSPINVOKE.SWIGPendingException.Pending) throw MMCoreCSPINVOKE.SWIGPendingException.Retrieve();
  }

  public static CharVector Repeat(char value, int count) {
    IntPtr cPtr = MMCoreCSPINVOKE.CharVector_Repeat(value, count);
    CharVector ret = (cPtr == IntPtr.Zero) ? null : new CharVector(cPtr, true);
    if (MMCoreCSPINVOKE.SWIGPendingException.Pending) throw MMCoreCSPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    MMCoreCSPINVOKE.CharVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    MMCoreCSPINVOKE.CharVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (MMCoreCSPINVOKE.SWIGPendingException.Pending) throw MMCoreCSPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, CharVector values) {
    MMCoreCSPINVOKE.CharVector_SetRange(swigCPtr, index, CharVector.getCPtr(values));
    if (MMCoreCSPINVOKE.SWIGPendingException.Pending) throw MMCoreCSPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(char value) {
    bool ret = MMCoreCSPINVOKE.CharVector_Contains(swigCPtr, value);
    return ret;
  }

  public int IndexOf(char value) {
    int ret = MMCoreCSPINVOKE.CharVector_IndexOf(swigCPtr, value);
    return ret;
  }

  public int LastIndexOf(char value) {
    int ret = MMCoreCSPINVOKE.CharVector_LastIndexOf(swigCPtr, value);
    return ret;
  }

  public bool Remove(char value) {
    bool ret = MMCoreCSPINVOKE.CharVector_Remove(swigCPtr, value);
    return ret;
  }

}

}
