/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace CWrapper {

using System;
using System.Runtime.InteropServices;

public class CMMError : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CMMError(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CMMError obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CMMError() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MMCoreCSPINVOKE.delete_CMMError(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

   public String getMessage() {
      return getMsg();
   }

  public CMMError(string msg, int code) : this(MMCoreCSPINVOKE.new_CMMError__SWIG_0(msg, code), true) {
  }

  public CMMError(string specificMsg, string coreMsg, int code) : this(MMCoreCSPINVOKE.new_CMMError__SWIG_1(specificMsg, coreMsg, code), true) {
  }

  public CMMError(int code) : this(MMCoreCSPINVOKE.new_CMMError__SWIG_2(code), true) {
  }

  public virtual string getMsg() {
    string ret = MMCoreCSPINVOKE.CMMError_getMsg(swigCPtr);
    return ret;
  }

  public int getCode() {
    int ret = MMCoreCSPINVOKE.CMMError_getCode(swigCPtr);
    return ret;
  }

  public void setCoreMsg(string msg) {
    MMCoreCSPINVOKE.CMMError_setCoreMsg(swigCPtr, msg);
  }

  public virtual string getCoreMsg() {
    string ret = MMCoreCSPINVOKE.CMMError_getCoreMsg(swigCPtr);
    return ret;
  }

}

}
