/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace CWrapper {

public enum DeviceType {
  UnknownType = 0,
  AnyType,
  CameraDevice,
  ShutterDevice,
  StateDevice,
  StageDevice,
  XYStageDevice,
  SerialDevice,
  GenericDevice,
  AutoFocusDevice,
  CoreDevice,
  ImageProcessorDevice,
  ImageStreamerDevice,
  SignalIODevice,
  MagnifierDevice,
  ProgrammableIODevice,
  SLMDevice,
  CommandDispatchDevice
}

}
