/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace CWrapper {

using System;
using System.Runtime.InteropServices;

public class MetadataSingleTag : MetadataTag {
  private HandleRef swigCPtr;

  internal MetadataSingleTag(IntPtr cPtr, bool cMemoryOwn) : base(MMCoreCSPINVOKE.MetadataSingleTagUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(MetadataSingleTag obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~MetadataSingleTag() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MMCoreCSPINVOKE.delete_MetadataSingleTag(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public MetadataSingleTag() : this(MMCoreCSPINVOKE.new_MetadataSingleTag__SWIG_0(), true) {
  }

  public MetadataSingleTag(string name, string device, bool readOnly) : this(MMCoreCSPINVOKE.new_MetadataSingleTag__SWIG_1(name, device, readOnly), true) {
  }

  public string GetValue() {
    string ret = MMCoreCSPINVOKE.MetadataSingleTag_GetValue(swigCPtr);
    return ret;
  }

  public void SetValue(string val) {
    MMCoreCSPINVOKE.MetadataSingleTag_SetValue(swigCPtr, val);
  }

  public override MetadataSingleTag ToSingleTag() {
    IntPtr cPtr = MMCoreCSPINVOKE.MetadataSingleTag_ToSingleTag(swigCPtr);
    MetadataSingleTag ret = (cPtr == IntPtr.Zero) ? null : new MetadataSingleTag(cPtr, false);
    return ret;
  }

  public override MetadataTag Clone() {
    IntPtr cPtr = MMCoreCSPINVOKE.MetadataSingleTag_Clone(swigCPtr);
    MetadataTag ret = (cPtr == IntPtr.Zero) ? null : new MetadataTag(cPtr, false);
    return ret;
  }

  public override string Serialize() {
    string ret = MMCoreCSPINVOKE.MetadataSingleTag_Serialize(swigCPtr);
    return ret;
  }

  public override bool Restore(string stream) {
    bool ret = MMCoreCSPINVOKE.MetadataSingleTag_Restore(swigCPtr, stream);
    return ret;
  }

}

}
