/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace CWrapper {

using System;
using System.Runtime.InteropServices;

public class MetadataArrayTag : MetadataTag {
  private HandleRef swigCPtr;

  internal MetadataArrayTag(IntPtr cPtr, bool cMemoryOwn) : base(MMCoreCSPINVOKE.MetadataArrayTagUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(MetadataArrayTag obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~MetadataArrayTag() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MMCoreCSPINVOKE.delete_MetadataArrayTag(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public MetadataArrayTag() : this(MMCoreCSPINVOKE.new_MetadataArrayTag(), true) {
  }

  public override MetadataArrayTag ToArrayTag() {
    IntPtr cPtr = MMCoreCSPINVOKE.MetadataArrayTag_ToArrayTag(swigCPtr);
    MetadataArrayTag ret = (cPtr == IntPtr.Zero) ? null : new MetadataArrayTag(cPtr, false);
    return ret;
  }

  public void AddValue(string val) {
    MMCoreCSPINVOKE.MetadataArrayTag_AddValue(swigCPtr, val);
  }

  public void SetValue(string val, uint idx) {
    MMCoreCSPINVOKE.MetadataArrayTag_SetValue(swigCPtr, val, idx);
  }

  public string GetValue(uint idx) {
    string ret = MMCoreCSPINVOKE.MetadataArrayTag_GetValue(swigCPtr, idx);
    return ret;
  }

  public uint GetSize() {
    uint ret = MMCoreCSPINVOKE.MetadataArrayTag_GetSize(swigCPtr);
    return ret;
  }

  public override MetadataTag Clone() {
    IntPtr cPtr = MMCoreCSPINVOKE.MetadataArrayTag_Clone(swigCPtr);
    MetadataTag ret = (cPtr == IntPtr.Zero) ? null : new MetadataTag(cPtr, false);
    return ret;
  }

  public override string Serialize() {
    string ret = MMCoreCSPINVOKE.MetadataArrayTag_Serialize(swigCPtr);
    return ret;
  }

  public override bool Restore(string stream) {
    bool ret = MMCoreCSPINVOKE.MetadataArrayTag_Restore(swigCPtr, stream);
    return ret;
  }

}

}
