/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace CWrapper {

using System;
using System.Runtime.InteropServices;

public class MMCoreCS {
  public static int MaxStrLength {
    get {
      int ret = MMCoreCSPINVOKE.MaxStrLength_get();
      return ret;
    } 
  }

  public static string g_Keyword_Name {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Name_get();
      return ret;
    } 
  }

  public static string g_Keyword_Description {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Description_get();
      return ret;
    } 
  }

  public static string g_Keyword_CameraName {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_CameraName_get();
      return ret;
    } 
  }

  public static string g_Keyword_CameraID {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_CameraID_get();
      return ret;
    } 
  }

  public static string g_Keyword_Binning {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Binning_get();
      return ret;
    } 
  }

  public static string g_Keyword_Exposure {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Exposure_get();
      return ret;
    } 
  }

  public static string g_Keyword_ActualExposure {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_ActualExposure_get();
      return ret;
    } 
  }

  public static string g_Keyword_ActualInterval_ms {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_ActualInterval_ms_get();
      return ret;
    } 
  }

  public static string g_Keyword_Interval_ms {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Interval_ms_get();
      return ret;
    } 
  }

  public static string g_Keyword_Elapsed_Time_ms {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Elapsed_Time_ms_get();
      return ret;
    } 
  }

  public static string g_Keyword_PixelType {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_PixelType_get();
      return ret;
    } 
  }

  public static string g_Keyword_ReadoutTime {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_ReadoutTime_get();
      return ret;
    } 
  }

  public static string g_Keyword_ReadoutMode {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_ReadoutMode_get();
      return ret;
    } 
  }

  public static string g_Keyword_Gain {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Gain_get();
      return ret;
    } 
  }

  public static string g_Keyword_EMGain {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_EMGain_get();
      return ret;
    } 
  }

  public static string g_Keyword_Offset {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Offset_get();
      return ret;
    } 
  }

  public static string g_Keyword_CCDTemperature {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_CCDTemperature_get();
      return ret;
    } 
  }

  public static string g_Keyword_CCDTemperatureSetPoint {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_CCDTemperatureSetPoint_get();
      return ret;
    } 
  }

  public static string g_Keyword_State {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_State_get();
      return ret;
    } 
  }

  public static string g_Keyword_Label {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Label_get();
      return ret;
    } 
  }

  public static string g_Keyword_Position {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Position_get();
      return ret;
    } 
  }

  public static string g_Keyword_Type {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Type_get();
      return ret;
    } 
  }

  public static string g_Keyword_Delay {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Delay_get();
      return ret;
    } 
  }

  public static string g_Keyword_BaudRate {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_BaudRate_get();
      return ret;
    } 
  }

  public static string g_Keyword_DataBits {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_DataBits_get();
      return ret;
    } 
  }

  public static string g_Keyword_StopBits {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_StopBits_get();
      return ret;
    } 
  }

  public static string g_Keyword_Parity {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Parity_get();
      return ret;
    } 
  }

  public static string g_Keyword_Handshaking {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Handshaking_get();
      return ret;
    } 
  }

  public static string g_Keyword_Port {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Port_get();
      return ret;
    } 
  }

  public static string g_Keyword_Speed {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Speed_get();
      return ret;
    } 
  }

  public static string g_Keyword_CoreDevice {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_CoreDevice_get();
      return ret;
    } 
  }

  public static string g_Keyword_CoreInitialize {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_CoreInitialize_get();
      return ret;
    } 
  }

  public static string g_Keyword_CoreCamera {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_CoreCamera_get();
      return ret;
    } 
  }

  public static string g_Keyword_CoreShutter {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_CoreShutter_get();
      return ret;
    } 
  }

  public static string g_Keyword_CoreXYStage {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_CoreXYStage_get();
      return ret;
    } 
  }

  public static string g_Keyword_CoreFocus {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_CoreFocus_get();
      return ret;
    } 
  }

  public static string g_Keyword_CoreAutoFocus {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_CoreAutoFocus_get();
      return ret;
    } 
  }

  public static string g_Keyword_CoreAutoShutter {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_CoreAutoShutter_get();
      return ret;
    } 
  }

  public static string g_Keyword_CoreChannelGroup {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_CoreChannelGroup_get();
      return ret;
    } 
  }

  public static string g_Keyword_CoreImageProcessor {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_CoreImageProcessor_get();
      return ret;
    } 
  }

  public static string g_Keyword_CoreSLM {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_CoreSLM_get();
      return ret;
    } 
  }

  public static string g_Keyword_CoreTimeoutMs {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_CoreTimeoutMs_get();
      return ret;
    } 
  }

  public static string g_Keyword_Channel {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Channel_get();
      return ret;
    } 
  }

  public static string g_Keyword_Version {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Version_get();
      return ret;
    } 
  }

  public static string g_Keyword_ColorMode {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_ColorMode_get();
      return ret;
    } 
  }

  public static string g_Keyword_Transpose_SwapXY {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Transpose_SwapXY_get();
      return ret;
    } 
  }

  public static string g_Keyword_Transpose_MirrorX {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Transpose_MirrorX_get();
      return ret;
    } 
  }

  public static string g_Keyword_Transpose_MirrorY {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Transpose_MirrorY_get();
      return ret;
    } 
  }

  public static string g_Keyword_Transpose_Correction {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Transpose_Correction_get();
      return ret;
    } 
  }

  public static string g_Keyword_Closed_Position {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Closed_Position_get();
      return ret;
    } 
  }

  public static string g_Keyword_Metadata_Z {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Metadata_Z_get();
      return ret;
    } 
  }

  public static string g_Keyword_Meatdata_Exposure {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Meatdata_Exposure_get();
      return ret;
    } 
  }

  public static string g_Keyword_Metadata_Score {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Metadata_Score_get();
      return ret;
    } 
  }

  public static string g_Keyword_Metadata_ImageNumber {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Metadata_ImageNumber_get();
      return ret;
    } 
  }

  public static string g_Keyword_Metadata_StartTime {
    get {
      string ret = MMCoreCSPINVOKE.g_Keyword_Metadata_StartTime_get();
      return ret;
    } 
  }

  public static string g_FieldDelimiters {
    get {
      string ret = MMCoreCSPINVOKE.g_FieldDelimiters_get();
      return ret;
    } 
  }

  public static string g_CFGCommand_Device {
    get {
      string ret = MMCoreCSPINVOKE.g_CFGCommand_Device_get();
      return ret;
    } 
  }

  public static string g_CFGCommand_Label {
    get {
      string ret = MMCoreCSPINVOKE.g_CFGCommand_Label_get();
      return ret;
    } 
  }

  public static string g_CFGCommand_Property {
    get {
      string ret = MMCoreCSPINVOKE.g_CFGCommand_Property_get();
      return ret;
    } 
  }

  public static string g_CFGCommand_Configuration {
    get {
      string ret = MMCoreCSPINVOKE.g_CFGCommand_Configuration_get();
      return ret;
    } 
  }

  public static string g_CFGCommand_ConfigGroup {
    get {
      string ret = MMCoreCSPINVOKE.g_CFGCommand_ConfigGroup_get();
      return ret;
    } 
  }

  public static string g_CFGCommand_Equipment {
    get {
      string ret = MMCoreCSPINVOKE.g_CFGCommand_Equipment_get();
      return ret;
    } 
  }

  public static string g_CFGCommand_Delay {
    get {
      string ret = MMCoreCSPINVOKE.g_CFGCommand_Delay_get();
      return ret;
    } 
  }

  public static string g_CFGCommand_ImageSynchro {
    get {
      string ret = MMCoreCSPINVOKE.g_CFGCommand_ImageSynchro_get();
      return ret;
    } 
  }

  public static string g_CFGCommand_ConfigPixelSize {
    get {
      string ret = MMCoreCSPINVOKE.g_CFGCommand_ConfigPixelSize_get();
      return ret;
    } 
  }

  public static string g_CFGCommand_PixelSize_um {
    get {
      string ret = MMCoreCSPINVOKE.g_CFGCommand_PixelSize_um_get();
      return ret;
    } 
  }

  public static string g_CFGGroup_System {
    get {
      string ret = MMCoreCSPINVOKE.g_CFGGroup_System_get();
      return ret;
    } 
  }

  public static string g_CFGGroup_System_Startup {
    get {
      string ret = MMCoreCSPINVOKE.g_CFGGroup_System_Startup_get();
      return ret;
    } 
  }

  public static string g_CFGGroup_System_Shutdown {
    get {
      string ret = MMCoreCSPINVOKE.g_CFGGroup_System_Shutdown_get();
      return ret;
    } 
  }

  public static string g_CFGGroup_PixelSizeUm {
    get {
      string ret = MMCoreCSPINVOKE.g_CFGGroup_PixelSizeUm_get();
      return ret;
    } 
  }

  public static int _DATABITS_5 {
    get {
      int ret = MMCoreCSPINVOKE._DATABITS_5_get();
      return ret;
    } 
  }

  public static int _DATABITS_6 {
    get {
      int ret = MMCoreCSPINVOKE._DATABITS_6_get();
      return ret;
    } 
  }

  public static int _DATABITS_7 {
    get {
      int ret = MMCoreCSPINVOKE._DATABITS_7_get();
      return ret;
    } 
  }

  public static int _DATABITS_8 {
    get {
      int ret = MMCoreCSPINVOKE._DATABITS_8_get();
      return ret;
    } 
  }

  public static int _FLOWCONTROL_NONE {
    get {
      int ret = MMCoreCSPINVOKE._FLOWCONTROL_NONE_get();
      return ret;
    } 
  }

  public static int _FLOWCONTROL_RTSCTS_IN {
    get {
      int ret = MMCoreCSPINVOKE._FLOWCONTROL_RTSCTS_IN_get();
      return ret;
    } 
  }

  public static int _FLOWCONTROL_RTSCTS_OUT {
    get {
      int ret = MMCoreCSPINVOKE._FLOWCONTROL_RTSCTS_OUT_get();
      return ret;
    } 
  }

  public static int _FLOWCONTROL_XONXOFF_IN {
    get {
      int ret = MMCoreCSPINVOKE._FLOWCONTROL_XONXOFF_IN_get();
      return ret;
    } 
  }

  public static int _FLOWCONTROL_XONXOFF_OUT {
    get {
      int ret = MMCoreCSPINVOKE._FLOWCONTROL_XONXOFF_OUT_get();
      return ret;
    } 
  }

  public static int _PARITY_EVEN {
    get {
      int ret = MMCoreCSPINVOKE._PARITY_EVEN_get();
      return ret;
    } 
  }

  public static int _PARITY_MARK {
    get {
      int ret = MMCoreCSPINVOKE._PARITY_MARK_get();
      return ret;
    } 
  }

  public static int _PARITY_NONE {
    get {
      int ret = MMCoreCSPINVOKE._PARITY_NONE_get();
      return ret;
    } 
  }

  public static int _PARITY_ODD {
    get {
      int ret = MMCoreCSPINVOKE._PARITY_ODD_get();
      return ret;
    } 
  }

  public static int _PARITY_SPACE {
    get {
      int ret = MMCoreCSPINVOKE._PARITY_SPACE_get();
      return ret;
    } 
  }

  public static int _STOPBITS_1 {
    get {
      int ret = MMCoreCSPINVOKE._STOPBITS_1_get();
      return ret;
    } 
  }

  public static int _STOPBITS_1_5 {
    get {
      int ret = MMCoreCSPINVOKE._STOPBITS_1_5_get();
      return ret;
    } 
  }

  public static int _STOPBITS_2 {
    get {
      int ret = MMCoreCSPINVOKE._STOPBITS_2_get();
      return ret;
    } 
  }

  public static readonly int MM_CODE_OK = MMCoreCSPINVOKE.MM_CODE_OK_get();
  public static readonly int MM_CODE_ERR = MMCoreCSPINVOKE.MM_CODE_ERR_get();
  public static readonly int DEVICE_OK = MMCoreCSPINVOKE.DEVICE_OK_get();
  public static readonly int DEVICE_ERR = MMCoreCSPINVOKE.DEVICE_ERR_get();
  public static readonly int DEVICE_INVALID_PROPERTY = MMCoreCSPINVOKE.DEVICE_INVALID_PROPERTY_get();
  public static readonly int DEVICE_INVALID_PROPERTY_VALUE = MMCoreCSPINVOKE.DEVICE_INVALID_PROPERTY_VALUE_get();
  public static readonly int DEVICE_DUPLICATE_PROPERTY = MMCoreCSPINVOKE.DEVICE_DUPLICATE_PROPERTY_get();
  public static readonly int DEVICE_INVALID_PROPERTY_TYPE = MMCoreCSPINVOKE.DEVICE_INVALID_PROPERTY_TYPE_get();
  public static readonly int DEVICE_NATIVE_MODULE_FAILED = MMCoreCSPINVOKE.DEVICE_NATIVE_MODULE_FAILED_get();
  public static readonly int DEVICE_UNSUPPORTED_DATA_FORMAT = MMCoreCSPINVOKE.DEVICE_UNSUPPORTED_DATA_FORMAT_get();
  public static readonly int DEVICE_INTERNAL_INCONSISTENCY = MMCoreCSPINVOKE.DEVICE_INTERNAL_INCONSISTENCY_get();
  public static readonly int DEVICE_NOT_SUPPORTED = MMCoreCSPINVOKE.DEVICE_NOT_SUPPORTED_get();
  public static readonly int DEVICE_UNKNOWN_LABEL = MMCoreCSPINVOKE.DEVICE_UNKNOWN_LABEL_get();
  public static readonly int DEVICE_UNSUPPORTED_COMMAND = MMCoreCSPINVOKE.DEVICE_UNSUPPORTED_COMMAND_get();
  public static readonly int DEVICE_UNKNOWN_POSITION = MMCoreCSPINVOKE.DEVICE_UNKNOWN_POSITION_get();
  public static readonly int DEVICE_NO_CALLBACK_REGISTERED = MMCoreCSPINVOKE.DEVICE_NO_CALLBACK_REGISTERED_get();
  public static readonly int DEVICE_SERIAL_COMMAND_FAILED = MMCoreCSPINVOKE.DEVICE_SERIAL_COMMAND_FAILED_get();
  public static readonly int DEVICE_SERIAL_BUFFER_OVERRUN = MMCoreCSPINVOKE.DEVICE_SERIAL_BUFFER_OVERRUN_get();
  public static readonly int DEVICE_SERIAL_INVALID_RESPONSE = MMCoreCSPINVOKE.DEVICE_SERIAL_INVALID_RESPONSE_get();
  public static readonly int DEVICE_SERIAL_TIMEOUT = MMCoreCSPINVOKE.DEVICE_SERIAL_TIMEOUT_get();
  public static readonly int DEVICE_SELF_REFERENCE = MMCoreCSPINVOKE.DEVICE_SELF_REFERENCE_get();
  public static readonly int DEVICE_NO_PROPERTY_DATA = MMCoreCSPINVOKE.DEVICE_NO_PROPERTY_DATA_get();
  public static readonly int DEVICE_DUPLICATE_LABEL = MMCoreCSPINVOKE.DEVICE_DUPLICATE_LABEL_get();
  public static readonly int DEVICE_INVALID_INPUT_PARAM = MMCoreCSPINVOKE.DEVICE_INVALID_INPUT_PARAM_get();
  public static readonly int DEVICE_BUFFER_OVERFLOW = MMCoreCSPINVOKE.DEVICE_BUFFER_OVERFLOW_get();
  public static readonly int DEVICE_NONEXISTENT_CHANNEL = MMCoreCSPINVOKE.DEVICE_NONEXISTENT_CHANNEL_get();
  public static readonly int DEVICE_INVALID_PROPERTY_LIMTS = MMCoreCSPINVOKE.DEVICE_INVALID_PROPERTY_LIMTS_get();
  public static readonly int DEVICE_SNAP_IMAGE_FAILED = MMCoreCSPINVOKE.DEVICE_SNAP_IMAGE_FAILED_get();
  public static readonly int DEVICE_IMAGE_PARAMS_FAILED = MMCoreCSPINVOKE.DEVICE_IMAGE_PARAMS_FAILED_get();
  public static readonly int DEVICE_CORE_FOCUS_STAGE_UNDEF = MMCoreCSPINVOKE.DEVICE_CORE_FOCUS_STAGE_UNDEF_get();
  public static readonly int DEVICE_CORE_EXPOSURE_FAILED = MMCoreCSPINVOKE.DEVICE_CORE_EXPOSURE_FAILED_get();
  public static readonly int DEVICE_CORE_CONFIG_FAILED = MMCoreCSPINVOKE.DEVICE_CORE_CONFIG_FAILED_get();
  public static readonly int DEVICE_CAMERA_BUSY_ACQUIRING = MMCoreCSPINVOKE.DEVICE_CAMERA_BUSY_ACQUIRING_get();
  public static readonly int DEVICE_INCOMPATIBLE_IMAGE = MMCoreCSPINVOKE.DEVICE_INCOMPATIBLE_IMAGE_get();
  public static readonly int DEVICE_CAN_NOT_SET_PROPERTY = MMCoreCSPINVOKE.DEVICE_CAN_NOT_SET_PROPERTY_get();
  public static readonly int DEVICE_CORE_CHANNEL_PRESETS_FAILED = MMCoreCSPINVOKE.DEVICE_CORE_CHANNEL_PRESETS_FAILED_get();
  public static readonly int DEVICE_LOCALLY_DEFINED_ERROR = MMCoreCSPINVOKE.DEVICE_LOCALLY_DEFINED_ERROR_get();
  public static readonly int DEVICE_NOT_CONNECTED = MMCoreCSPINVOKE.DEVICE_NOT_CONNECTED_get();
}

}
