/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace CWrapper {

using System;
using System.Runtime.InteropServices;

public class MMEventCallback : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MMEventCallback(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(MMEventCallback obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~MMEventCallback() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MMCoreCSPINVOKE.delete_MMEventCallback(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public MMEventCallback() : this(MMCoreCSPINVOKE.new_MMEventCallback(), true) {
  }

  public virtual void onPropertiesChanged() {
    MMCoreCSPINVOKE.MMEventCallback_onPropertiesChanged(swigCPtr);
  }

  public virtual void onCoordinateUpdate() {
    MMCoreCSPINVOKE.MMEventCallback_onCoordinateUpdate(swigCPtr);
  }

}

}
