/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace CWrapper {

using System;
using System.Runtime.InteropServices;

public class PropertySetting : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PropertySetting(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PropertySetting obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PropertySetting() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MMCoreCSPINVOKE.delete_PropertySetting(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public PropertySetting(string deviceLabel, string prop, string value, bool readOnly) : this(MMCoreCSPINVOKE.new_PropertySetting__SWIG_0(deviceLabel, prop, value, readOnly), true) {
  }

  public PropertySetting(string deviceLabel, string prop, string value) : this(MMCoreCSPINVOKE.new_PropertySetting__SWIG_1(deviceLabel, prop, value), true) {
  }

  public PropertySetting() : this(MMCoreCSPINVOKE.new_PropertySetting__SWIG_2(), true) {
  }

  public string getDeviceLabel() {
    string ret = MMCoreCSPINVOKE.PropertySetting_getDeviceLabel(swigCPtr);
    return ret;
  }

  public string getPropertyName() {
    string ret = MMCoreCSPINVOKE.PropertySetting_getPropertyName(swigCPtr);
    return ret;
  }

  public bool getReadOnly() {
    bool ret = MMCoreCSPINVOKE.PropertySetting_getReadOnly(swigCPtr);
    return ret;
  }

  public string getPropertyValue() {
    string ret = MMCoreCSPINVOKE.PropertySetting_getPropertyValue(swigCPtr);
    return ret;
  }

  public string getKey() {
    string ret = MMCoreCSPINVOKE.PropertySetting_getKey(swigCPtr);
    return ret;
  }

  public static string generateKey(string device, string prop) {
    string ret = MMCoreCSPINVOKE.PropertySetting_generateKey(device, prop);
    return ret;
  }

  public string Serialize() {
    string ret = MMCoreCSPINVOKE.PropertySetting_Serialize(swigCPtr);
    return ret;
  }

  public void Restore(string data) {
    MMCoreCSPINVOKE.PropertySetting_Restore(swigCPtr, data);
    if (MMCoreCSPINVOKE.SWIGPendingException.Pending) throw MMCoreCSPINVOKE.SWIGPendingException.Retrieve();
  }

  public string getVerbose() {
    string ret = MMCoreCSPINVOKE.PropertySetting_getVerbose(swigCPtr);
    return ret;
  }

  public bool isEqualTo(PropertySetting ps) {
    bool ret = MMCoreCSPINVOKE.PropertySetting_isEqualTo(swigCPtr, PropertySetting.getCPtr(ps));
    if (MMCoreCSPINVOKE.SWIGPendingException.Pending) throw MMCoreCSPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
