/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace CWrapper {

using System;
using System.Runtime.InteropServices;

public class PropertyPair : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PropertyPair(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PropertyPair obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PropertyPair() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MMCoreCSPINVOKE.delete_PropertyPair(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public PropertyPair(string prop, string value) : this(MMCoreCSPINVOKE.new_PropertyPair__SWIG_0(prop, value), true) {
  }

  public PropertyPair() : this(MMCoreCSPINVOKE.new_PropertyPair__SWIG_1(), true) {
  }

  public string getPropertyName() {
    string ret = MMCoreCSPINVOKE.PropertyPair_getPropertyName(swigCPtr);
    return ret;
  }

  public string getPropertyValue() {
    string ret = MMCoreCSPINVOKE.PropertyPair_getPropertyValue(swigCPtr);
    return ret;
  }

}

}
