/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace CWrapper {

using System;
using System.Runtime.InteropServices;

public class PropertyBlock : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PropertyBlock(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PropertyBlock obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PropertyBlock() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MMCoreCSPINVOKE.delete_PropertyBlock(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public PropertyBlock() : this(MMCoreCSPINVOKE.new_PropertyBlock(), true) {
  }

  public void addPair(PropertyPair pair) {
    MMCoreCSPINVOKE.PropertyBlock_addPair(swigCPtr, PropertyPair.getCPtr(pair));
    if (MMCoreCSPINVOKE.SWIGPendingException.Pending) throw MMCoreCSPINVOKE.SWIGPendingException.Retrieve();
  }

  public PropertyPair getPair(uint index) {
    PropertyPair ret = new PropertyPair(MMCoreCSPINVOKE.PropertyBlock_getPair(swigCPtr, index), true);
    if (MMCoreCSPINVOKE.SWIGPendingException.Pending) throw MMCoreCSPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint size() {
    uint ret = MMCoreCSPINVOKE.PropertyBlock_size(swigCPtr);
    return ret;
  }

  public string getValue(string key) {
    string ret = MMCoreCSPINVOKE.PropertyBlock_getValue(swigCPtr, key);
    if (MMCoreCSPINVOKE.SWIGPendingException.Pending) throw MMCoreCSPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
